# Generated by Django 3.0.7 on 2022-07-15 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plants',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('kind', models.CharField(max_length=200, null=True)),
                ('height', models.IntegerField(null=True)),
                ('complexity', models.CharField(choices=[('Master', 'master'), ('Middle', 'middle'), ('Beginner', 'beginner')], max_length=200, null=True)),
                ('lighting', models.CharField(choices=[('Sunny', 'sunny'), ('Half-shade', 'half-shade'), ('Dark', 'dark')], max_length=200, null=True)),
                ('waterfreq', models.IntegerField(null=True)),
            ],
            options={
                'verbose_name': 'Цветок',
                'verbose_name_plural': 'Цветы',
                'ordering': ('name',),
            },
        ),
    ]
