# Generated by Django 3.0.7 on 2022-07-15 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_room'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='rname',
            new_name='name',
        ),
    ]
